// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: regen/divvy/v1/query.proto

package divvy

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryAllocator struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryAllocator) Reset()         { *m = QueryAllocator{} }
func (m *QueryAllocator) String() string { return proto.CompactTextString(m) }
func (*QueryAllocator) ProtoMessage()    {}
func (*QueryAllocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_bde75e31310101ac, []int{0}
}
func (m *QueryAllocator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllocator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllocator.Merge(m, src)
}
func (m *QueryAllocator) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllocator) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllocator.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllocator proto.InternalMessageInfo

type QueryAllocatorsResp struct {
	Allocator []Allocator `protobuf:"bytes,1,rep,name=allocator,proto3" json:"allocator"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllocatorsResp) Reset()         { *m = QueryAllocatorsResp{} }
func (m *QueryAllocatorsResp) String() string { return proto.CompactTextString(m) }
func (*QueryAllocatorsResp) ProtoMessage()    {}
func (*QueryAllocatorsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_bde75e31310101ac, []int{1}
}
func (m *QueryAllocatorsResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllocatorsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllocatorsResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllocatorsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllocatorsResp.Merge(m, src)
}
func (m *QueryAllocatorsResp) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllocatorsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllocatorsResp.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllocatorsResp proto.InternalMessageInfo

type QueryAllocators struct {
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllocators) Reset()         { *m = QueryAllocators{} }
func (m *QueryAllocators) String() string { return proto.CompactTextString(m) }
func (*QueryAllocators) ProtoMessage()    {}
func (*QueryAllocators) Descriptor() ([]byte, []int) {
	return fileDescriptor_bde75e31310101ac, []int{2}
}
func (m *QueryAllocators) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllocators) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllocators.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllocators) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllocators.Merge(m, src)
}
func (m *QueryAllocators) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllocators) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllocators.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllocators proto.InternalMessageInfo

type QueryAllocatorsByOwner struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllocatorsByOwner) Reset()         { *m = QueryAllocatorsByOwner{} }
func (m *QueryAllocatorsByOwner) String() string { return proto.CompactTextString(m) }
func (*QueryAllocatorsByOwner) ProtoMessage()    {}
func (*QueryAllocatorsByOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_bde75e31310101ac, []int{3}
}
func (m *QueryAllocatorsByOwner) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllocatorsByOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllocatorsByOwner.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllocatorsByOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllocatorsByOwner.Merge(m, src)
}
func (m *QueryAllocatorsByOwner) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllocatorsByOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllocatorsByOwner.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllocatorsByOwner proto.InternalMessageInfo

func init() {
	proto.RegisterType((*QueryAllocator)(nil), "regen.divvy.v1.QueryAllocator")
	proto.RegisterType((*QueryAllocatorsResp)(nil), "regen.divvy.v1.QueryAllocatorsResp")
	proto.RegisterType((*QueryAllocators)(nil), "regen.divvy.v1.QueryAllocators")
	proto.RegisterType((*QueryAllocatorsByOwner)(nil), "regen.divvy.v1.QueryAllocatorsByOwner")
}

func init() { proto.RegisterFile("regen/divvy/v1/query.proto", fileDescriptor_bde75e31310101ac) }

var fileDescriptor_bde75e31310101ac = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xf6, 0xa5, 0x14, 0x94, 0xab, 0x54, 0xc4, 0x51, 0xa1, 0x60, 0x55, 0x6e, 0xe4, 0x8a, 0x12,
	0x05, 0xf5, 0x8e, 0x84, 0x99, 0x81, 0x0c, 0x30, 0x30, 0x00, 0xd9, 0x60, 0xbb, 0x24, 0x4f, 0x87,
	0x45, 0xea, 0xe7, 0xfa, 0x2e, 0x2e, 0x56, 0xd5, 0x85, 0x8d, 0x0d, 0xc1, 0xcc, 0xff, 0xc9, 0x58,
	0x89, 0x85, 0x09, 0x41, 0xc2, 0x0f, 0x41, 0x3e, 0xbb, 0x4d, 0x6c, 0x14, 0x82, 0x3a, 0xf9, 0xce,
	0xef, 0x7b, 0xdf, 0xf7, 0xbd, 0xef, 0xd9, 0xd4, 0x8d, 0x41, 0x41, 0x28, 0x46, 0x41, 0x92, 0xa4,
	0x22, 0xe9, 0x88, 0xe3, 0x09, 0xc4, 0x29, 0x8f, 0x62, 0x34, 0xc8, 0xb6, 0x6d, 0x8d, 0xdb, 0x1a,
	0x4f, 0x3a, 0xee, 0x8e, 0x42, 0x85, 0xb6, 0x24, 0xb2, 0x53, 0x8e, 0x72, 0x77, 0x15, 0xa2, 0x1a,
	0x83, 0x90, 0x51, 0x20, 0x64, 0x18, 0xa2, 0x91, 0x26, 0xc0, 0x50, 0x17, 0xd5, 0xf6, 0x10, 0xf5,
	0x11, 0x6a, 0x31, 0x90, 0x1a, 0x72, 0x72, 0x91, 0x74, 0x06, 0x60, 0x64, 0x47, 0x44, 0x52, 0x05,
	0xa1, 0x05, 0x17, 0xd8, 0xaa, 0x17, 0x93, 0x46, 0x50, 0xf0, 0xf8, 0x6d, 0xba, 0xfd, 0x2a, 0xeb,
	0x7e, 0x32, 0x1e, 0xe3, 0x50, 0x1a, 0x8c, 0x59, 0x83, 0xde, 0x90, 0xa3, 0x51, 0x0c, 0x5a, 0x37,
	0x48, 0x93, 0xb4, 0xea, 0xfd, 0x8b, 0xab, 0xff, 0x95, 0xd0, 0xdb, 0x65, 0xb0, 0xee, 0x83, 0x8e,
	0xd8, 0x63, 0x5a, 0x97, 0x17, 0x6f, 0x1a, 0xa4, 0xb9, 0xd1, 0xda, 0xea, 0xde, 0xe5, 0xe5, 0x19,
	0xf9, 0x65, 0x4b, 0xef, 0xda, 0xf4, 0xc7, 0x9e, 0xd3, 0x5f, 0x74, 0xb0, 0x67, 0x94, 0x2e, 0x2c,
	0x37, 0x6a, 0x4d, 0xd2, 0xda, 0xea, 0xde, 0xe7, 0xf9, 0x7c, 0x3c, 0x9b, 0x8f, 0xe7, 0xe1, 0x15,
	0xf3, 0xf1, 0x97, 0x52, 0x41, 0xa6, 0x8b, 0xa1, 0x86, 0xfe, 0x52, 0xab, 0xff, 0x9a, 0xde, 0xac,
	0xd8, 0x63, 0x4f, 0x4b, 0xdc, 0xc4, 0x72, 0x1f, 0xac, 0xe5, 0x3e, 0x9e, 0x80, 0x36, 0x25, 0xea,
	0x84, 0xde, 0xa9, 0x50, 0xf7, 0xd2, 0x17, 0x27, 0x21, 0xc4, 0x6c, 0x87, 0x6e, 0x62, 0x76, 0x28,
	0xc2, 0xca, 0x2f, 0x15, 0xdd, 0xda, 0x55, 0x75, 0xbb, 0x1f, 0x37, 0xe8, 0xa6, 0x15, 0x66, 0x9a,
	0xd6, 0x17, 0x3b, 0xf2, 0xaa, 0xf1, 0x96, 0xcd, 0xb9, 0xab, 0xe3, 0xf7, 0x1f, 0x7c, 0xf8, 0xf6,
	0xfb, 0x4b, 0xed, 0x1e, 0xdb, 0x17, 0x95, 0xaf, 0xe2, 0x72, 0x21, 0xe2, 0xb4, 0x58, 0xf8, 0x19,
	0x4b, 0x28, 0x5d, 0x0a, 0x73, 0xef, 0xdf, 0xaa, 0xda, 0xdd, 0x5f, 0x03, 0xc8, 0xb6, 0xe6, 0xfb,
	0xd6, 0xc0, 0x2e, 0x73, 0x57, 0x1a, 0xd0, 0xec, 0x33, 0xa1, 0xb7, 0xfe, 0x8e, 0xfa, 0x60, 0x0d,
	0x7d, 0x81, 0xfb, 0x3f, 0x1b, 0x0f, 0xad, 0x8d, 0x36, 0x6b, 0xad, 0xb6, 0x21, 0xec, 0x2e, 0xc5,
	0xa9, 0x7d, 0x9c, 0xf5, 0x9e, 0x4f, 0x7f, 0x79, 0xce, 0x74, 0xe6, 0x91, 0xf3, 0x99, 0x47, 0x7e,
	0xce, 0x3c, 0xf2, 0x69, 0xee, 0x39, 0xe7, 0x73, 0xcf, 0xf9, 0x3e, 0xf7, 0x9c, 0x37, 0x87, 0x2a,
	0x30, 0x6f, 0x27, 0x03, 0x3e, 0xc4, 0xa3, 0x9c, 0xf1, 0x30, 0x04, 0x73, 0x82, 0xf1, 0xbb, 0xe2,
	0x36, 0x86, 0x91, 0x82, 0x58, 0xbc, 0xcf, 0x85, 0x06, 0xd7, 0xed, 0xef, 0xf7, 0xe8, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x6e, 0x99, 0x09, 0x59, 0x28, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Allocator(ctx context.Context, in *QueryAllocator, opts ...grpc.CallOption) (*Allocator, error)
	Allocators(ctx context.Context, in *QueryAllocators, opts ...grpc.CallOption) (*QueryAllocatorsResp, error)
	AllocatorsByOwner(ctx context.Context, in *QueryAllocatorsByOwner, opts ...grpc.CallOption) (*QueryAllocatorsResp, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Allocator(ctx context.Context, in *QueryAllocator, opts ...grpc.CallOption) (*Allocator, error) {
	out := new(Allocator)
	err := c.cc.Invoke(ctx, "/regen.divvy.v1.Query/Allocator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Allocators(ctx context.Context, in *QueryAllocators, opts ...grpc.CallOption) (*QueryAllocatorsResp, error) {
	out := new(QueryAllocatorsResp)
	err := c.cc.Invoke(ctx, "/regen.divvy.v1.Query/Allocators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllocatorsByOwner(ctx context.Context, in *QueryAllocatorsByOwner, opts ...grpc.CallOption) (*QueryAllocatorsResp, error) {
	out := new(QueryAllocatorsResp)
	err := c.cc.Invoke(ctx, "/regen.divvy.v1.Query/AllocatorsByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Allocator(context.Context, *QueryAllocator) (*Allocator, error)
	Allocators(context.Context, *QueryAllocators) (*QueryAllocatorsResp, error)
	AllocatorsByOwner(context.Context, *QueryAllocatorsByOwner) (*QueryAllocatorsResp, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Allocator(ctx context.Context, req *QueryAllocator) (*Allocator, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocator not implemented")
}
func (*UnimplementedQueryServer) Allocators(ctx context.Context, req *QueryAllocators) (*QueryAllocatorsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocators not implemented")
}
func (*UnimplementedQueryServer) AllocatorsByOwner(ctx context.Context, req *QueryAllocatorsByOwner) (*QueryAllocatorsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocatorsByOwner not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Allocator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllocator)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Allocator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regen.divvy.v1.Query/Allocator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Allocator(ctx, req.(*QueryAllocator))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Allocators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllocators)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Allocators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regen.divvy.v1.Query/Allocators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Allocators(ctx, req.(*QueryAllocators))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllocatorsByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllocatorsByOwner)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllocatorsByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regen.divvy.v1.Query/AllocatorsByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllocatorsByOwner(ctx, req.(*QueryAllocatorsByOwner))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "regen.divvy.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocator",
			Handler:    _Query_Allocator_Handler,
		},
		{
			MethodName: "Allocators",
			Handler:    _Query_Allocators_Handler,
		},
		{
			MethodName: "AllocatorsByOwner",
			Handler:    _Query_AllocatorsByOwner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "regen/divvy/v1/query.proto",
}

func (m *QueryAllocator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllocator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllocator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllocatorsResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllocatorsResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllocatorsResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Allocator) > 0 {
		for iNdEx := len(m.Allocator) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Allocator[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllocators) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllocators) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllocators) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllocatorsByOwner) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllocatorsByOwner) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllocatorsByOwner) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryAllocator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllocatorsResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Allocator) > 0 {
		for _, e := range m.Allocator {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllocators) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllocatorsByOwner) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryAllocator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllocator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllocator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllocatorsResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllocatorsResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllocatorsResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allocator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Allocator = append(m.Allocator, Allocator{})
			if err := m.Allocator[len(m.Allocator)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllocators) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllocators: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllocators: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllocatorsByOwner) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllocatorsByOwner: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllocatorsByOwner: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
